"""initial schema

Revision ID: 7db19999eb26
Revises: 
Create Date: 2026-09-23 11:04:00.801113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7db19999eb26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('show_in_nav', sa.Boolean(), nullable=False),
    sa.Column('nav_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('rate_limits',
    sa.Column('key', sa.String(length=190), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('lang', sa.String(length=2), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'lang', name='uq_site_setting')
    )
    op.create_table('slug_redirects',
    sa.Column('old_slug', sa.String(length=40), nullable=False),
    sa.Column('target_type', sa.String(length=10), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('old_slug')
    )
    op.create_table('space_tombstones',
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('purged_at', sa.DateTime(), nullable=False),
    sa.Column('reserved_until', sa.DateTime(), nullable=False),
    sa.Column('reason_kind', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('task_runs',
    sa.Column('task', sa.String(length=40), nullable=False),
    sa.Column('last_started_at', sa.DateTime(), nullable=True),
    sa.Column('last_finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('task')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('ui_lang', sa.String(length=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('session_token', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('object_type', sa.String(length=20), nullable=False),
    sa.Column('object_id', sa.String(length=60), nullable=False),
    sa.Column('diff', sa.JSON(), nullable=True),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_at'), ['at'], unique=False)

    op.create_table('blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_type', sa.String(length=10), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.String(length=2), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blocks', schema=None) as batch_op:
        batch_op.create_index('ix_blocks_owner', ['owner_type', 'owner_id', 'lang', 'position'], unique=False)

    op.create_table('login_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('login_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_type', sa.String(length=10), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('storage_key', sa.String(length=200), nullable=False),
    sa.Column('mime', sa.String(length=40), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('alt_text', sa.String(length=300), nullable=False),
    sa.Column('variants', sa.JSON(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_index('ix_media_owner', ['owner_type', 'owner_id'], unique=False)

    op.create_table('page_translations',
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.String(length=2), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('meta_description', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('page_id', 'lang')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.CheckConstraint("role IN ('webmaster', 'superadmin')", name='ck_user_roles_role'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role')
    )
    op.create_table('maker_spaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('tagline', sa.String(length=200), nullable=False),
    sa.Column('bio_html', sa.Text(), nullable=False),
    sa.Column('discipline', sa.String(length=80), nullable=False),
    sa.Column('lang', sa.String(length=2), nullable=False),
    sa.Column('accent_color', sa.String(length=7), nullable=False),
    sa.Column('avatar_media_id', sa.Integer(), nullable=True),
    sa.Column('cover_media_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('hidden_at', sa.DateTime(), nullable=True),
    sa.Column('purge_at', sa.DateTime(), nullable=True),
    sa.Column('hidden_by', sa.Integer(), nullable=True),
    sa.Column('hide_reason', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("lang IN ('nl', 'en')", name='ck_space_lang'),
    sa.CheckConstraint("status IN ('draft', 'published', 'hidden')", name='ck_space_status'),
    sa.ForeignKeyConstraint(['avatar_media_id'], ['media.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cover_media_id'], ['media.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hidden_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # §3a purge cap: dialect-specific expression (MariaDB is the real target, SQLite is dev/tests).
    if op.get_bind().dialect.name == 'mysql':
        op.create_check_constraint('ck_space_purge_cap', 'maker_spaces',
                                   'purge_at IS NULL OR purge_at <= hidden_at + INTERVAL 365 DAY')
    elif op.get_bind().dialect.name == 'sqlite':
        with op.batch_alter_table('maker_spaces') as batch:
            batch.create_check_constraint('ck_space_purge_cap',
                                          "purge_at IS NULL OR purge_at <= datetime(hidden_at, '+365 days')")
    op.create_table('space_members',
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['maker_spaces.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('space_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('space_members')
    op.drop_table('maker_spaces')
    op.drop_table('user_roles')
    op.drop_table('page_translations')
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index('ix_media_owner')

    op.drop_table('media')
    with op.batch_alter_table('login_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_tokens_user_id'))

    op.drop_table('login_tokens')
    with op.batch_alter_table('blocks', schema=None) as batch_op:
        batch_op.drop_index('ix_blocks_owner')

    op.drop_table('blocks')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_at'))

    op.drop_table('audit_log')
    op.drop_table('users')
    op.drop_table('task_runs')
    op.drop_table('space_tombstones')
    op.drop_table('slug_redirects')
    op.drop_table('site_settings')
    op.drop_table('rate_limits')
    op.drop_table('pages')
    # ### end Alembic commands ###
